name: Check Chocolatey on Windows

on:
  workflow_dispatch:

jobs:
  check-choco:
    runs-on: windows-latest
    steps:
      - name: Проверка наличия Chocolatey
        shell: pwsh
        run: |
          if (Get-Command choco.exe -ErrorAction SilentlyContinue) {
            Write-Host "✅ Chocolatey уже установлен."
          } else {
            Write-Host "⚠️ Chocolatey не найден. Устанавливаем..."
            Set-ExecutionPolicy Bypass -Scope Process -Force
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }

      - name: Проверка версии Chocolatey
        shell: pwsh
        run: choco --version
