name: Build PHP
run-name: Build PHP ${{ inputs.php-version }}
on:
  workflow_dispatch:
    inputs:
      php-version:
        description: 'PHP version to build'
        required: true
      upload:
        type: choice
        options: ['true', 'false']
        description: Upload artifacts to the downloads server
        required: false
        default: 'true'

jobs:
  php:
    strategy:
      matrix:
        arch: [x64]
        ts: [nts, ts]
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./php
        with:
          php-version: ${{ github.event.inputs.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}

  artifacts:
    runs-on: ubuntu-latest
    needs: php
    outputs:
      artifact-id: ${{ steps.artifacts.outputs.artifact-id }}
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact/merge@v4
        id: artifacts
        with:
          name: artifacts
          delete-merged: true
 
